version: '3.3'

services:
  users-db:
    container_name: users-db
    build: ./users-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build: ./users-service
    ports:
      - 3000:3000
    depends_on: 
      - users-db
